import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { isDone, validateTicket } from '../public/domain.js';
import { DEMO_AGENTS, DEMO_NOTE, demoTickets } from './demo-data.js';
import { listTickets, summarizeTickets } from './query.js';

const { Pool } = pg;
const fields = ['title', 'description', 'requester', 'email', 'category', 'tags', 'priority', 'status', 'assigneeId', 'dueAt'];
const columns = fields.map(field => `"${field}"`).join(', ');
const placeholders = fields.map((_, index) => `$${index + 1}`).join(', ');
const demoAgents = DEMO_AGENTS.map(([id, name, initials]) => ({ id, name, initials }));

function fail(code, status = 400, fields) {
  throw Object.assign(new Error(code), { code, status, fields });
}

function validated(input) {
  if (!input || typeof input !== 'object' || Array.isArray(input)) fail('invalidRequest');
  const errors = validateTicket(input, demoAgents);
  if (Object.keys(errors).length) fail('validation', 422, errors);
  return Object.fromEntries(fields.map(field => [field, typeof input[field] === 'string' ? input[field].trim() : input[field]]));
}

function valuesFor(input) {
  return fields.map(field => field === 'tags' ? JSON.stringify(input.tags) : input[field]);
}

export function createPostgresStore({ connectionString = process.env.DATABASE_URL || process.env.POSTGRES_URL, pool: suppliedPool } = {}) {
  let pool = suppliedPool;
  let readyPromise;

  function getPool() {
    if (!pool) {
      if (!connectionString) throw new Error('DATABASE_URL or POSTGRES_URL is required for the hosted demo');
      pool = new Pool({ connectionString, max: 2, idleTimeoutMillis: 10000, connectionTimeoutMillis: 20000 });
      pool.on('error', error => console.error('PostgreSQL connection error:', error));
    }
    return pool;
  }

  async function event(client, ticketId, type, payload, date = new Date().toISOString()) {
    await client.query('INSERT INTO events ("ticketId", type, payload, "createdAt") VALUES ($1, $2, $3, $4)', [ticketId, type, JSON.stringify(payload), date]);
  }

  async function insertWith(client, input, date = new Date().toISOString()) {
    const data = validated(input);
    const result = await client.query(
      `INSERT INTO tickets (${columns}, "createdAt", "updatedAt", "resolvedAt") VALUES (${placeholders}, $11, $12, $13) RETURNING *`,
      [...valuesFor(data), date, date, isDone(data) ? date : null],
    );
    const ticket = result.rows[0];
    await event(client, ticket.id, 'created', {}, date);
    return ticket;
  }

  async function initialize() {
    const client = await getPool().connect();
    try {
      await client.query('BEGIN');
      // Multiple function instances may start together. Only one seeds the demo.
      await client.query('SELECT pg_advisory_xact_lock(713641)');
      await client.query('CREATE TABLE IF NOT EXISTS agents (id integer PRIMARY KEY, name text NOT NULL, initials text NOT NULL)');
      await client.query(`CREATE TABLE IF NOT EXISTS tickets (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title text NOT NULL, description text NOT NULL, requester text NOT NULL, email text NOT NULL,
        category text NOT NULL, tags jsonb NOT NULL, priority text NOT NULL, status text NOT NULL,
        "assigneeId" integer NOT NULL REFERENCES agents(id), "createdAt" text NOT NULL,
        "updatedAt" text NOT NULL, "dueAt" text NOT NULL, "resolvedAt" text,
        version integer NOT NULL DEFAULT 1
      )`);
      await client.query(`CREATE TABLE IF NOT EXISTS events (
        id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "ticketId" integer NOT NULL REFERENCES tickets(id), type text NOT NULL,
        payload jsonb NOT NULL, "createdAt" text NOT NULL
      )`);
      await client.query('CREATE TABLE IF NOT EXISTS undos (token text PRIMARY KEY, snapshots jsonb NOT NULL, "expiresAt" bigint NOT NULL)');
      await client.query('CREATE INDEX IF NOT EXISTS events_ticket ON events ("ticketId", id)');
      for (const [id, name, initials] of DEMO_AGENTS) {
        await client.query('INSERT INTO agents (id, name, initials) VALUES ($1, $2, $3) ON CONFLICT (id) DO NOTHING', [id, name, initials]);
      }
      const { rows } = await client.query('SELECT EXISTS (SELECT 1 FROM tickets) AS seeded');
      if (!rows[0].seeded) {
        for (const { input, date, noteAt } of demoTickets()) {
          const ticket = await insertWith(client, input, date);
          if (noteAt) await event(client, ticket.id, 'note', { text: DEMO_NOTE }, noteAt);
        }
      }
      await client.query('COMMIT');
    } catch (error) {
      await client.query('ROLLBACK').catch(() => {});
      throw error;
    } finally {
      client.release();
    }
  }

  function ready() {
    if (!readyPromise) readyPromise = initialize().catch(error => {
      readyPromise = undefined;
      throw error;
    });
    return readyPromise;
  }

  async function transaction(action) {
    await ready();
    const client = await getPool().connect();
    try {
      await client.query('BEGIN');
      const result = await action(client);
      await client.query('COMMIT');
      return result;
    } catch (error) {
      await client.query('ROLLBACK').catch(() => {});
      throw error;
    } finally {
      client.release();
    }
  }

  async function getWith(client, id, lock = false) {
    const result = await client.query(`SELECT * FROM tickets WHERE id = $1${lock ? ' FOR UPDATE' : ''}`, [id]);
    return result.rows[0] || null;
  }

  async function lockedTickets(client, ids) {
    const placeholders = ids.map((_, index) => `$${index + 1}`).join(', ');
    return (await client.query(`SELECT * FROM tickets WHERE id IN (${placeholders}) ORDER BY id FOR UPDATE`, ids)).rows;
  }

  async function updateOne(client, old, input, undo = false) {
    const next = validated({ ...old, ...input });
    const changes = fields.filter(field => JSON.stringify(old[field]) !== JSON.stringify(next[field])).map(field => ({ field, from: old[field], to: next[field] }));
    if (!changes.length) return old;
    const date = new Date().toISOString();
    const resolvedAt = undo ? input.resolvedAt : isDone(next) ? old.resolvedAt || date : null;
    const assignments = fields.map((field, index) => `"${field}" = $${index + 1}`).join(', ');
    const result = await client.query(
      `UPDATE tickets SET ${assignments}, "updatedAt" = $11, "resolvedAt" = $12, version = version + 1 WHERE id = $13 RETURNING *`,
      [...valuesFor(next), date, resolvedAt, old.id],
    );
    await event(client, old.id, undo ? 'undo' : 'updated', { changes });
    return result.rows[0];
  }

  async function remember(client, snapshots, updated) {
    await client.query('DELETE FROM undos WHERE "expiresAt" < $1', [Date.now()]);
    const token = randomUUID();
    const record = snapshots.map((ticket, index) => ({ ticket, version: updated[index].version }));
    await client.query('INSERT INTO undos (token, snapshots, "expiresAt") VALUES ($1, $2, $3)', [token, JSON.stringify(record), Date.now() + 60000]);
    return token;
  }

  async function agents() {
    await ready();
    return (await getPool().query('SELECT id, name, initials FROM agents ORDER BY id')).rows;
  }

  async function get(id) {
    await ready();
    return getWith(getPool(), id);
  }

  async function all() {
    await ready();
    return (await getPool().query('SELECT * FROM tickets ORDER BY id DESC')).rows;
  }

  async function list(query = {}) {
    return listTickets(await all(), query);
  }

  async function summary(period = 7) {
    return summarizeTickets(await all(), period);
  }

  async function insert(input) {
    return transaction(client => insertWith(client, input));
  }

  async function update(id, input) {
    return transaction(async client => {
      const old = await getWith(client, id, true);
      if (!old) fail('notFound', 404);
      if (input.version !== old.version) fail('conflict', 409);
      const ticket = await updateOne(client, old, input);
      return { ticket, undoToken: ticket.version !== old.version ? await remember(client, [old], [ticket]) : null };
    });
  }

  async function bulk(body) {
    const ids = body.ids;
    if (!Array.isArray(ids) || !ids.length || ids.length > 100 || ids.some(id => !Number.isInteger(id)) || new Set(ids).size !== ids.length) fail('invalidRequest');
    if (!body.changes || typeof body.changes !== 'object' || Object.keys(body.changes).some(key => !['status', 'assigneeId'].includes(key)) || !Object.keys(body.changes).length) fail('invalidRequest');
    return transaction(async client => {
      const rows = await lockedTickets(client, ids);
      const byId = new Map(rows.map(ticket => [ticket.id, ticket]));
      const snapshots = ids.map(id => {
        const ticket = byId.get(id);
        if (!ticket) fail('notFound', 404);
        if (body.versions?.[id] !== ticket.version) fail('conflict', 409);
        return ticket;
      });
      const tickets = [];
      for (const ticket of snapshots) tickets.push(await updateOne(client, ticket, body.changes));
      return { tickets, undoToken: await remember(client, snapshots, tickets) };
    });
  }

  async function undo(token) {
    return transaction(async client => {
      const record = (await client.query('SELECT snapshots, "expiresAt" FROM undos WHERE token = $1 FOR UPDATE', [token])).rows[0];
      if (!record || Number(record.expiresAt) < Date.now()) fail('undoExpired', 409);
      const snapshots = record.snapshots;
      const ids = snapshots.map(snapshot => snapshot.ticket.id);
      const rows = await lockedTickets(client, ids);
      const byId = new Map(rows.map(ticket => [ticket.id, ticket]));
      if (snapshots.some(snapshot => byId.get(snapshot.ticket.id)?.version !== snapshot.version)) fail('conflict', 409);
      const tickets = [];
      for (const snapshot of snapshots) tickets.push(await updateOne(client, byId.get(snapshot.ticket.id), snapshot.ticket, true));
      await client.query('DELETE FROM undos WHERE token = $1', [token]);
      return { tickets };
    });
  }

  async function note(id, text, version) {
    if (typeof text !== 'string' || !text.trim() || text.trim().length > 2000) fail('validation', 422, { note: 'noteInvalid' });
    return transaction(async client => {
      const ticket = await getWith(client, id, true);
      if (!ticket) fail('notFound', 404);
      if (version !== ticket.version) fail('conflict', 409);
      await event(client, id, 'note', { text: text.trim() });
      const result = await client.query('UPDATE tickets SET "updatedAt" = $1, version = version + 1 WHERE id = $2 RETURNING *', [new Date().toISOString(), id]);
      return result.rows[0];
    });
  }

  async function history(id) {
    await ready();
    return (await getPool().query('SELECT * FROM events WHERE "ticketId" = $1 ORDER BY id DESC', [id])).rows;
  }

  return { ready, agents, get, all, list, summary, insert, update, bulk, undo, note, history };
}
